### ISSUE TITLE
Passport使用新版知乎日报时遇见的问题

### ISSUE THREAD

**Issue by FreemanZ** [BBDev-CN/zhihu#6]
1、Passport的键盘滑动得到了支持，但是只支持上下滑动而没有支持左右滑动；
2、在查看具体内容中，触屏上下滑动时左右抖动严重，经常出现不小心返回到首页。

**Comment by MerrickZ** [comment]
1，目前为止没有哪个应用是键盘滑动返回上一层的，可以做，不过可能会影响使用
2，这个将分列为issue #7

**Comment by MerrickZ** [comment]
#7 已修复 ，代码 稍后上传。
